# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: targetDART
# author:
#   name: Jannis Klinkenberg
#   email: j.klinkenberg@itc.rwth-aachen.de
description: >- # this means to ignore newlines until "baseurl:"
  TargetDART is a BMBF funded project focussing on on the development of adaptive and reactive task migration targeting CPUs and GPUs in heterogeneous exascale systems. The project is a collaboration between the TU Munich, the HLRS and the RWTH Aachen.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

minima:
  skin: dark
  
  date_format: "%b %-d, %Y"
  
  # generate social links in footer
  social_links:
    - { platform: RWTH,           user_url: "https://help.itc.rwth-aachen.de/" }
    - { platform: TUM,            user_url: "https://www.lrz.de/" }
    - { platform: HLRS,           user_url: "https://www.hlrs.de/" }
    - { platform: github,         user_url: "https://github.com/orgs/targetDART/repositories" }

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
